# Generated by Django 6.0.5 on 2026-06-05 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_rule_metric_alter_rule_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('ACKNOWLEDGED', 'ACKNOWLEDGED'), ('RESOLVED', 'RESOLVED')], default='OPEN', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.workspace')),
            ],
        ),
    ]
