# Generated by Django 6.0.5 on 2026-06-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_incident'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
