# Generated by Django 6.0.5 on 2026-06-10 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_rcainsight_rootcauseanalysis_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255)),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=50)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='TrendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('current_value', models.FloatField()),
                ('previous_value', models.FloatField()),
                ('change_percentage', models.FloatField()),
                ('trend_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.workspace')),
            ],
        ),
    ]
