# Generated by Django 6.0.5 on 2026-06-30 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_riskprediction_unique_prediction_per_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=255)),
                ('score', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='healthscore',
            constraint=models.UniqueConstraint(fields=('workspace', 'node_id'), name='unique_workspace_node_health'),
        ),
        migrations.AddField(
            model_name='healthscorehistory',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_history', to='monitoring.workspace'),
        ),
        migrations.AddIndex(
            model_name='healthscorehistory',
            index=models.Index(fields=['workspace', 'node_id', '-created_at'], name='monitoring__workspa_4b42ae_idx'),
        ),
    ]
