# Generated by Django 6.0.5 on 2026-06-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_healthscorehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
