# Generated by Django 6.0.5 on 2026-06-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_rule_resolved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='resolved_at',
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
